specVersion: 0.0.1
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/ws?apikey=ec9800c1-55be-4ffc-bb9e-f80233f4e1b3
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: runtime
    kind: substrate/Runtime
    # for kusama startBlock: 1445458
    startBlock: 4445458
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession